### ISSUE TITLE
Update React to 15.5

### ISSUE THREAD

**Issue by ColCh** [Lingvokot/lingvokot.github.io#22]
Breaking change, requires manual adjustments
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by ColCh** [comment]
Wait about one week from release date (April 7, 2017) before actual updating

E.g. until April 14, 2017

**Comment by keshan3262** [comment]
Well, I updated React to 15.5.4 in my local.
After this I got this error during build: [error.txt](https://github.com/Lingvokot/lingvokot.github.io/files/921861/error.txt)


So I'm afraid this issue will be closed much later

**Comment by ColCh** [comment]
Yeah, no hurry in this update
