### ISSUE TITLE
Repair layout

### ISSUE THREAD

**Issue by ColCh** [Lingvokot/lingvokot.github.io#30]
Something is broken since 1-2 deploys
[![http://i.imgur.com/Iw3Qo4Fm.png](http://i.imgur.com/Iw3Qo4Fm.png)](http://imgur.com/a/mGwLc)

**Comment by ColCh** [comment]
It seems that it wants to load minified semantic js and css from `/semantic/`, but that directory is removed by https://github.com/Lingvokot/lingvokot.github.io/issues/20 . 

Actually, this https://github.com/Lingvokot/lingvokot.github.io/issues/28 will fix current issue

**Comment by ColCh** [comment]
So we should just check if layout is repaired after https://github.com/Lingvokot/lingvokot.github.io/issues/28 will be done

**Comment by keshan3262** [comment]
All recent issues are indeed because the page wants to load minified semantic js and css from /semantic/

**Comment by ColCh** [comment]
Aye, we just want to bundle jquery+semantic ui+app code into single css bundle and js bundle via webpack settings
