### ISSUE TITLE
Contact form adjustment

### ISSUE THREAD

**Issue by ColCh** [Lingvokot/lingvokot.github.io#31]
As https://github.com/Lingvokot/lingvokot.github.io/issues/9 , it seems that it sends data somewhere?

But where is that spreadsheet

And we don't experience Slack messages on form submit

**Comment by keshan3262** [comment]
The spreadsheet is here: https://docs.google.com/spreadsheets/d/1AgqLUUxiLuIJn_I-v2LHdPIbWw08La7ybuM9wqUFGDQ/edit?usp=sharing
Also I get e-mail if somebody fills the form

**Comment by ColCh** [comment]
Gotta reopen this issue until we finish complete setup of the form

**Comment by a1n1** [comment]
Guys, in the end pls, request spreadsheet link from me. I hope I will be the owner of this google sheet and share all needed access. Also, pls add channel name #investors in slack for notifications.

**Comment by ColCh** [comment]
Working project code: https://github.com/Lingvokot/google-form-to-slack

Demo:
![image](https://cloud.githubusercontent.com/assets/599439/25286142/5bd33616-26c5-11e7-92ef-c512bca9f4e5.png)


now we need access to Google form @a1n1 : https://docs.google.com/forms/

**Comment by ColCh** [comment]
Spreadsheet column names can be changed nicely:

![image](https://cloud.githubusercontent.com/assets/599439/25286231/b8943058-26c5-11e7-86bb-d22aececff77.png)

results in this Slack message
![image](https://cloud.githubusercontent.com/assets/599439/25286225/ae24531e-26c5-11e7-9770-7a1ca56eddce.png)

**Comment by keshan3262** [comment]
Slack messages work now well but all sending was made not with the help of Google Forms.
The spreadsheet with script is here: https://docs.google.com/spreadsheets/d/1AgqLUUxiLuIJn_I-v2LHdPIbWw08La7ybuM9wqUFGDQ/edit?usp=sharing
Also I get e-mail if somebody fills the form

**Comment by keshan3262** [comment]
@a1n1 please send your spreadsheet link
Or I missed something?

**Comment by ColCh** [comment]
A bit. Spreadsheet is attached to Form (so we don't need link from @a1n1 )

ok I will check all things now

~Can you push changes for form layout on website?~
