### ISSUE TITLE
Redesign prev/next buttons in carousel

### ISSUE THREAD

**Issue by ColCh** [Lingvokot/lingvokot.github.io#32]
This requires some discussion on how it should look like. Any ideas?

**Comment by keshan3262** [comment]
Maybe this?
![arrow](https://cloud.githubusercontent.com/assets/10885399/25065263/4d925be0-2215-11e7-9bd5-4ee66dc46b4c.png)
However, there were no such buttons in model at all
Oh, it should be scaled
