### ISSUE TITLE
Check if Carousel is working nicely with >1 element count

### ISSUE THREAD

**Issue by ColCh** [Lingvokot/lingvokot.github.io#33]
This means: add some item to carousel and see how it works.
This not means that we want testing item in carousel on production site - only check will be enough

Please assign yourself to this issue.

To confirm working, record some screen video and share it somewhere (e.g. https://streamable.com/ )

**Comment by keshan3262** [comment]
https://streamable.com/fn875
Here the data sample from test/components/OurApps.spec.js was used

**Comment by ColCh** [comment]
Nice! happy to close this issue
