### ISSUE TITLE
Fix lint errors, add lint check to test pipeline

### ISSUE THREAD

**Issue by ColCh** [Lingvokot/lingvokot.github.io#39]
After build will be green again https://github.com/Lingvokot/lingvokot.github.io/pull/27

**Comment by keshan3262** [comment]
Sorry, can this issue be closed for now?

**Comment by ColCh** [comment]
No, we need to add lint check into test pipeline

**Comment by ColCh** [comment]
- Command: `eslint --cache --color --config .eslintrc 'src/**/*.js'` (npm's scripts, named `lint`)

- then, add correct npm's `test` script to be `npm run test:karma:sauce  && npm run lint`


That's it. You can do it, if you want :) I'm busy a bit this time, sorry
