### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by keshan3262** [Lingvokot/lingvokot.github.io#4]
`npm run build` writes message `[ 'TypeError: Cannot read property \'createElement\' of undefined\n    at handleJsonp (main:734:1699)\n    at Object.getRequest (main:734:2678)\n    at Object.init (main:734:5067)\n    at Object.Reqwest (main:734:3074)\n    at reqwest (main:734:5121)\n    at t.value (main:395:1383)\n    at d.mountComponent (main:603:4275)\n    at d.i [as mountComponent] (main:34:404)\n    at Object.mountComponent (main:58:157)\n    at b.mountChildren (main:645:1718)' ]`. However, the page is still displayed as expected.

**Comment by ColCh** [comment]
Is it related to build process scripts really or to React components itself? If first, then  I can collaborate on this issue

**Comment by ColCh** [comment]
BTW `carousel` branch get merged by now : #6

**Comment by keshan3262** [comment]
After I started usage of jQuery, `npm run build` returns another message:
`[ 'ReferenceError: $ is not defined\n    at t.value (main:386:2530)\n    at d._renderValidatedComponentWithoutOwnerOrContext (main:603:9245)\n    at d._renderValidatedComponent (main:603:9421)\n    at d.i [as _renderValidatedComponent] (main:34:404)\n    at d.mountComponent (main:603:4397)\n    at d.i [as mountComponent] (main:34:404)\n    at Object.mountComponent (main:58:157)\n    at b.mountChildren (main:645:1718)\n    at b._createContentMarkup (main:609:10471)\n    at b.mountComponent (main:609:9371)' ]`
If `document.querySelector` is used instead, the build process returns this:
`[ 'ReferenceError: document is not defined\n    at t.value (main:386:2551)\n    at d._renderValidatedComponentWithoutOwnerOrContext (main:603:9245)\n    at d._renderValidatedComponent (main:603:9421)\n    at d.i [as _renderValidatedComponent] (main:34:404)\n    at d.mountComponent (main:603:4397)\n    at d.i [as mountComponent] (main:34:404)\n    at Object.mountComponent (main:58:157)\n    at b.mountChildren (main:645:1718)\n    at b._createContentMarkup (main:609:10471)\n    at b.mountComponent (main:609:9371)' ]`
So I think that the build fails just because `document` global variable is used even in some library

**Comment by ColCh** [comment]
Yes, this is because jquery ( [required by semantic ui](https://semantic-ui.com/introduction/getting-started.html#include-in-your-html) ) requires DOM and there is no DOM on nodejs (build script has nodejs environment)

Solution is, use jquery-free semantic UI

Take a look on Semantic UI React: https://react.semantic-ui.com/introduction, it doesn’t depend on jQuery

**Comment by keshan3262** [comment]
When I commented out loading info about applications from App Store with `reqwest` in OurApps.js and `onWindowScroll` method in Navbar.js, build succeeded

**Comment by ColCh** [comment]
Lets see. We actually don't want to carousel content deployed in html (so it means that we don't want to execute `reqwest` at build step)

Solution - check against environment. If env is *browser-like*, then do a request. If no - then do nothing.

**Comment by ColCh** [comment]
I will push env variable inject via webpack for a moment
