### ISSUE TITLE
Fix React unmatching prerendered layout

### ISSUE THREAD

**Issue by ColCh** [Lingvokot/lingvokot.github.io#41]
We use server render, which have no DOM

React throws error when mounting. It can't validate prerendered tree, then wipes everything and renders from scratch

That's not good, mobile devices will experience rare lag during page load

Error itself

```
main.js:16 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) rue-active" offset="-49" data-reactid=".
 (server) rue-active" offset="0" data-reactid=".76
```

Thrown by this thing (selected)

![image](https://cloud.githubusercontent.com/assets/599439/25044587/1e8d73ec-2130-11e7-84ac-6828ca908ce5.png)

This is NavBar component: https://github.com/Lingvokot/lingvokot.github.io/blob/58121600149518824c6737d1ad3f45463b53c7a7/src/components/Navbar.js#L52-L53

Solution:  this actually looks like hack. Do we really need it?

**Comment by keshan3262** [comment]
Well, I don't know any better solution for now.
Height of navigation bar varies on mobile devices, tablets and PCs, so it is necessary to calculate the offset dynamically.

**Comment by ColCh** [comment]
Hm, but what is that offset for?

**Comment by keshan3262** [comment]
It controls scrolling in such way that you can scroll to the link plus or minus several pixels. I remember my "playing" with this parameter at first times. Without offset the link was behind navigation bar.

**Comment by keshan3262** [comment]
Well, I'll try now to remove this offset.

**Comment by keshan3262** [comment]
Well, I did it. And after clicking on "Technologies" link I got this:
![spectacle j26850](https://cloud.githubusercontent.com/assets/10885399/25064997/4b9fa3a2-220f-11e7-9292-396652a33a03.png)

**Comment by ColCh** [comment]
Ok, I've moved that adjustment into ComponentDidMount. It's working as it was (before I removed it), but now it uses server rendered version without error

See attached PR: https://github.com/Lingvokot/lingvokot.github.io/pull/42
