### ISSUE TITLE
Form look on iPhone 6 is wrong

### ISSUE THREAD

**Issue by ColCh** [Lingvokot/lingvokot.github.io#69]
it should be in all width of screen

![image](https://user-images.githubusercontent.com/599439/30364234-060c4eb6-986c-11e7-84be-44634bf5cf35.png)

**Comment by keshan3262** [comment]
Screen width is 750px, right?

**Comment by ColCh** [comment]
Oh, can't say right now, sorry.   Please use chrome device emulation in devtools

https://developers.google.com/web/tools/chrome-devtools/device-mode/
