### ISSUE TITLE
Write and use e2e test 

### ISSUE THREAD

**Issue by ColCh** [Lingvokot/lingvokot.github.io#8]
Simple test to open web page in the browser and see no errors (no exceptions)

This will turn CI semaphore green

**Comment by ColCh** [comment]
we have [karma](https://karma-runner.github.io/1.0/index.html) config for [sauce labs](https://saucelabs.com/) as ready-to-go, so we can use it to render main app component and expect no exceptions are thrown

**Comment by keshan3262** [comment]
Now tests are passed successfully on all browsers but for IE. I don't know why

**Comment by ColCh** [comment]
Can I take a look on any debug output?

**Comment by keshan3262** [comment]
https://travis-ci.org/Lingvokot/lingvokot.github.io/builds/218603114
Also interesting output is here:
https://travis-ci.org/Lingvokot/lingvokot.github.io/builds/218589252

**Comment by ColCh** [comment]
Please ping me back with how it works with Edge

**Comment by keshan3262** [comment]
https://travis-ci.org/Lingvokot/lingvokot.github.io/builds/219640296
This is called "Why? Because!"

**Comment by ColCh** [comment]
Resolving issue #19 will finally resolve current issue 😀
