### ISSUE TITLE
Rework contact form

### ISSUE THREAD

**Issue by ColCh** [Lingvokot/lingvokot.github.io#9]
We want to get notified about people who submitted our form.

Two options applicable:

* e-mail
* slack message

**Comment by keshan3262** [comment]
Excuse me, maybe I don't understand this task
Is this suitable (https://www.w3schools.com/html/tryit.asp?filename=tryhtml_form_mail)?

**Comment by ColCh** [comment]
AFAIK, Firebase is free, so may be we can use it. Ref: http://stackoverflow.com/questions/41035602/firebase-static-hosting-with-a-simple-contact-form

But this point needs some investigation

**Comment by keshan3262** [comment]
Well, what about Google Spreadsheet scripts?
Like this: https://github.com/dwyl/html-form-send-email-via-google-script-without-server

**Comment by ColCh** [comment]
Wow, it's very cool! This is actually what we need

And for sending Slack notification: https://github.com/scleveland/google-form-to-slack
Or: https://gist.github.com/andychase/e0b1eaa1b9ecc00ef2d2
